version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: list of the products
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null            
          - name: purchase_price
            description: the price of the product purchase
      - name: sales
        identifier: raw_gz_sales
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS timestamp)"
        description: list of all the sales
        columns:
          - name: date_date
            description: date of the purchase
          - name: order_id
            description: unique id of the order
          - name: products_id
            description: unique id of the product
          - name: qty
            description: quantity of products purchased
                 
      - name: ship
        identifier: raw_gz_ship
        description: all the fees related to shipping
        columns:
          - name: orders_id
            description: primary key of the table 
            tests:
              - unique
              - not_null                
          - name: shipping_fee
            description: the fee of the ship
          - name: log_cost
            description: the cost of logistics
          - name: ship_cost
            description: the cost of the shipping

      - name: bing
        identifier: raw_gz_bing
        description: the performace of bing in terms of marketing
        columns:
          - name: date_date
            description: the date of the marketing operation          
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: the name of the campaign
          - name: ads_cost
            description: the cost of the ads
          - name: impression
            description: the number of impressions     
          - name: click
            description: the number of click 

      - name: adwords
        identifier: raw_gz_adwords
        description: the performace of bing in terms of marketing
        columns:
          - name: date_date
            description: the date of the marketing operation          
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: the name of the campaign
          - name: ads_cost
            description: the cost of the ads
          - name: impression
            description: the number of impressions     
          - name: click
            description: the number of click 
      - name: criteo
        identifier: raw_gz_criteo
        description: the performace of bing in terms of marketing
        columns:
          - name: date_date
            description: the date of the marketing operation          
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: the name of the campaign
          - name: ads_cost
            description: the cost of the ads
          - name: impression
            description: the number of impressions     
          - name: click
            description: the number of click 

      - name: facebook
        identifier: raw_gz_facebook
        description: the performace of bing in terms of marketing
        columns:
          - name: date_date
            description: the date of the marketing operation          
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: the name of the campaign
          - name: ads_cost
            description: the cost of the ads
          - name: impression
            description: the number of impressions     
          - name: click
            description: the number of click 

models:
  - name: int_sales_margin
    description: table of the sales margin calculation
    columns:
      - name: (orders_id||"_"||pdt_id)
        description: primary key of the table 
        tests:
          - unique
          - not_null  

  - name: int_orders_margin
    description: table of the margin calculation
    columns:
      - name: orders_id
        description: primary key of the table 
        tests:
          - unique
          - not_null
                                   
  - name: int_orders_operational
    description: table of the operational costs calculation
    columns:
      - name: orders_id
        description: primary key of the table 
        tests:
          - unique
          - not_null          
  - name: int_campaigns
    description: table of all the campaigns
    columns:
      - name: campaign_primary_key
        description: primary key of the table 
        tests:
          - unique
          - not_null    

  - name: int_campaigns_day
    description: table of all the costs by date
    columns:
      - name: date_date
        description: primary key of the table 
        tests:
          - unique
          - not_null
  - name: finance_campaigns_day
    description: table of all the costs by + the ads_margin
    columns:
      - name: date_date
        description: primary key of the table 
        tests:
          - unique
          - not_null
      